"""empty message

Revision ID: 247e01bdffa4
Revises: 5e24fcfd1001
Create Date: 2019-06-17 17:55:13.663015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '247e01bdffa4'
down_revision = '5e24fcfd1001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_identities_uid_provider_index', table_name='user_identities')
    op.drop_table('user_identities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identities',
    sa.Column('inserted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], name='user_identities_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_identities_pkey')
    )
    op.create_index('user_identities_uid_provider_index', 'user_identities', ['uid', 'provider'], unique=True)
    # ### end Alembic commands ###
