"""empty message

Revision ID: 5e24fcfd1001
Revises: c3a91dc740a8
Create Date: 2019-06-17 13:57:01.849648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e24fcfd1001'
down_revision = 'c3a91dc740a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('inserted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('app_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('policy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['accounts.id'], name='collections_app_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collections_pkey')
    )
    # ### end Alembic commands ###
