"""empty message

Revision ID: c3a91dc740a8
Revises: b90edae803fc
Create Date: 2019-06-14 13:46:27.337806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a91dc740a8'
down_revision = 'b90edae803fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('salt_timestamp', sa.String(length=48), nullable=True))
    op.add_column('accounts', sa.Column('token_salt', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'token_salt')
    op.drop_column('accounts', 'salt_timestamp')
    # ### end Alembic commands ###
