"""added function table

Revision ID: d8b355e7f3a2
Revises: 60b3839d3384
Create Date: 2019-07-15 10:36:51.869019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b355e7f3a2'
down_revision = '60b3839d3384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions',
    sa.Column('inserted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functions_app_id'), 'functions', ['app_id'], unique=False)
    op.add_column('policies', sa.Column('read_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'read_only')
    op.drop_index(op.f('ix_functions_app_id'), table_name='functions')
    op.drop_table('functions')
    # ### end Alembic commands ###
