"""
Django settings for ancile_web project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
from config import loader as config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.abspath(os.curdir)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.SERVER_DEBUG

LOGIN_URL = "/login"

ALLOWED_HOSTS = [config.SERVER_NAME]

LOGIN_REDIRECT_URL = LOGOUT_REDIRECT_URL = "/"
# Application definition

INSTALLED_APPS = [
    "ancile.web.dashboard.apps.DashboardConfig",
    "ancile.web.api.apps.ApiConfig",
    "ancile.web.oauth.apps.OauthConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    "rest_framework",
    "rest_framework.authtoken",
    'corsheaders'
]

CRISPY_TEMPLATE_PACK = "bootstrap3"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = "ancile.web.ancile_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["ancile/web/dashboard/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "ancile.web.ancile_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": config.DATABASE_CONFIG
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "dashboard.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = config.LANGUAGE_CODE

TIME_ZONE = config.TIME_ZONE

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "ancile/web" + STATIC_URL)

if config.ENABLE_LOGGING:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
                "datefmt": "%d/%b/%Y %H:%M:%S",
            },
            "simple": {"format": "%(levelname)s %(message)s"},
        },
        "handlers": {
            "file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": "logs/info.log",
                "formatter": "verbose",
                "maxBytes": 1024 * 1024 * 15,
                "backupCount": 10,
            },
            "console": {
                "class": "logging.StreamHandler",
                "stream": sys.stdout,
                "formatter": "verbose",
            },
            "console-info": {
                "class": "logging.StreamHandler",
                "stream": sys.stdout,
                "formatter": "verbose",
                "level": "INFO",
            },
        },
        "loggers": {
            "": {"handlers": ["file"], "level": "DEBUG"},
            "django": {
                "handlers": ["file", "console-info"],
                "propagate": False,
                "level": "DEBUG",
            },
            "gunicorn.access":{
                "propagate": False,
                "handlers": ["file", "console"],
                "level": "INFO"
            },
            "ancile.core": {
                "level": "DEBUG",
                "propagate": False,
                "handlers": ["file", "console"],
            },
            "ancile.web.api": {"level": "INFO", "propagate": False, "handlers": ["file", "console"]},
            "ancile.web.oauth": {"level": "INFO", "propagate": False, "handlers": ["file", "console"]},
        },
    }

if config.SERVER_DEBUG:
    CORS_ORIGIN_REGEX_WHITELIST = [
        'http://localhost',
    ]