# Change these before deployment
SERVER_NAME: "localhost"
SECRET_KEY: "super-secret"
SERVER_DEBUG: False

LOGGING: True
CACHE: True
LANGUAGE_CODE: "en-us"
TIME_ZONE: "Etc/GMT-4"


database:
    ENGINE: "django.db.backends.postgresql"
    USER: "postgres"
    PASSWORD: "postgres"
    HOST: "db"
    PORT: "5432"
    NAME: "ancile_db"

redis:
    host: redis 
    port: 6379
    db: 1
