# Generated by Django 2.2.3 on 2019-07-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_token_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='scopes',
            field=models.ManyToManyField(null=True, to='dashboard.Scope'),
        ),
    ]
