# Generated by Django 2.2.3 on 2019-07-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190726_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.TextField(),
        ),
    ]
