# Generated by Django 2.2.3 on 2019-07-29 14:38

import bcrypt
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190726_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='predefinedpolicy',
            options={'verbose_name': 'Predefined policy', 'verbose_name_plural': 'Predefined policies'},
        ),
        migrations.AlterModelOptions(
            name='privatedata',
            options={'verbose_name': 'Private data', 'verbose_name_plural': 'Private data'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='app',
            name='salt_timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='token_salt',
            field=models.CharField(default=bcrypt.gensalt, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='function',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privatedata',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='privatedata',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='private_data:unique_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('name', 'provider'), name='scope:unique_scope_provider'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='token:unique_user_provider'),
        ),
    ]
