# Generated by Django 2.2.3 on 2019-07-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190729_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='read_only',
        ),
    ]
