# Generated by Django 2.2.3 on 2019-07-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190729_2159'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='permissiongroup',
            constraint=models.UniqueConstraint(fields=('name', 'app'), name='permission_group:unique_name_app'),
        ),
    ]
