# Generated by Django 2.2.3 on 2019-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190729_2308'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scope',
            name='scope:unique_scope_provider',
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('value', 'provider'), name='scope:unique_scope_provider'),
        ),
    ]
