# Generated by Django 2.2.3 on 2019-07-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190729_2316'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['user', 'app'], name='dashboard_p_user_id_a7c223_idx'),
        ),
    ]
