# Generated by Django 2.2.3 on 2019-07-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190729_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataprovider',
            old_name='name',
            new_name='path_name',
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='display_name',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
