# Generated by Django 2.2.3 on 2019-07-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20190730_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedpolicy',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
