# Generated by Django 2.2.4 on 2019-09-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_pendingdeveloper'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovider',
            name='provider_type',
            field=models.TextField(default='OAUTH'),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='access_token_url',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='auth_url',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='client_id',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='client_secret',
            field=models.TextField(default=None),
        ),
    ]
