# Generated by Django 2.2.4 on 2019-10-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190925_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_developer',
        ),
        migrations.AddField(
            model_name='user',
            name='developer_status',
            field=models.TextField(default='False'),
        ),
        migrations.DeleteModel(
            name='PendingDeveloper',
        ),
    ]
