"""empty message

Revision ID: 60b3839d3384
Revises: da042c8f9b71
Create Date: 2019-06-29 22:58:04.378200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b3839d3384'
down_revision = 'da042c8f9b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'access_token',
                    existing_type=sa.String(length=256),
                    type_=sa.String(length=3000),
                    existing_nullable=False)
    op.alter_column('tokens', 'refresh_token',
                    existing_type=sa.String(length=256),
                    type_=sa.String(length=3000))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'access_token',
                    existing_type=sa.String(length=3000),
                    type_=sa.String(length=256),
                    existing_nullable=False)
    op.alter_column('tokens', 'refresh_token',
                    existing_type=sa.String(length=3000),
                    type_=sa.String(length=256))
    # ### end Alembic commands ###
