"""empty message

Revision ID: 60b3839d3384
Revises: da042c8f9b71
Create Date: 2019-06-29 22:58:04.378200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b3839d3384'
down_revision = 'da042c8f9b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'access_token')
    op.drop_column('tokens', 'refresh_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('refresh_token', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('tokens', sa.Column('access_token', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
