"""changed private_data_name

Revision ID: da042c8f9b71
Revises: 247e01bdffa4
Create Date: 2019-06-19 17:22:54.562120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da042c8f9b71'
down_revision = '247e01bdffa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('private_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('tokens', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('tokens', 'private_data')
    # ### end Alembic commands ###
