"""added predefined policy table and policy group table

Revision ID: dfbb63fe5d03
Revises: d8b355e7f3a2
Create Date: 2019-07-16 16:18:22.139635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbb63fe5d03'
down_revision = 'd8b355e7f3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('app_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_group_app_id'), 'policy_group', ['app_id'], unique=False)
    op.create_table('predefined_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('purpose', sa.String(length=255), server_default=sa.text('NULL::character varying'), nullable=True),
    sa.Column('policy', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('app_id', sa.BigInteger(), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['policy_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predefined_policies_app_id'), 'predefined_policies', ['app_id'], unique=False)
    op.create_index(op.f('ix_predefined_policies_group_id'), 'predefined_policies', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predefined_policies_group_id'), table_name='predefined_policies')
    op.drop_index(op.f('ix_predefined_policies_app_id'), table_name='predefined_policies')
    op.drop_table('predefined_policies')
    op.drop_index(op.f('ix_policy_group_app_id'), table_name='policy_group')
    op.drop_table('policy_group')
    # ### end Alembic commands ###
